theme: minima
title: ACSE
description: A description has to go here, but for now it is just this msg.
tagline: this is the tagline
logo: /assets/img/logo.png
show_downloads: true



author:
  name:  Inaki Lopez
  email: ignore@gmail.com
  social:
    twitter: ilodev
    github:  ilodev
  about: Hi, just a small bio about...
